### PR TITLE
Add Facebook URL for course about pages

### PR DESCRIPTION
**Pull request by caesar2164**

### CODE REVIEW

**Comment by stvstnfrd** [comment]
@caesar2164 Has this been tested on the sandbox yet?

**Comment by caesar2164** [comment]
It has not, I didn't end up installing sandbox. There was enough to do as it was...

**Comment by stvstnfrd** [comment]
@caesar2164 Have you tested it locally?

**Comment by caesar2164** [comment]
yes, I got it to show up and work.

**Comment by stvstnfrd** [comment]
@caesar2164 This was never merged because you need to rebase your branch first..

**Comment by caesar2164** [comment]
@stvstnfrd rebased.

I also added a commit to remove the now unnecessary comment about Twitter.

**Comment by stvstnfrd** [comment]
I cherry-picked manually, so I'm closing this...

**Pull request closed without merging**
